#Port
server:
  port: '9091'

#DMDS
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open-library
    username: root
    password: root

  #LSFB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  #Devtool
  devtools:
    restart:
      enabled: 'true'

  #EnableColouredLogging
  output:
    ansi:
      enabled: always

  #App_Name
  application:
    name: OpenLibrary

#open_library_api
GET_API: https://openlibrary.org/isbn/

#open_library_base_URL
Base_URL: https://openlibrary.org

#ErrorMessage
ErrorMsg: Exception while getting book information

#Logging
logging:
  level:
    com:
      scalex:
        openlibrary: DEBUG